name: Run Bot for Metaculus AI Benchmark Tournament

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *" # Runs every 20 minutes

# Add concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

# Daily job to run the forecast bot
jobs:
  bot_gemini_2_5_pro_gemini_2_5_pro_grounding:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_5_PRO_GEMINI_2_5_PRO_GROUNDING'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_PRO_GEMINI_2_5_PRO_GROUNDING }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gemini_2_5_pro_sonar_reasoning_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_5_PRO_SONAR_REASONING_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_PRO_SONAR_REASONING_PRO }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gemini_2_5_exa_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_5_EXA_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_EXA_PRO }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_deepseek_r1_sonar_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_SONAR_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_SONAR_PRO }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_deepseek_r1_sonar:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_SONAR'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_SONAR }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_deepseek_r1_sonar_deep_research:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_SONAR_DEEP_RESEARCH'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_SONAR_DEEP_RESEARCH }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_deepseek_r1_sonar_reasoning_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_SONAR_REASONING_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_SONAR_REASONING_PRO }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_deepseek_r1_sonar_reasoning:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_SONAR_REASONING'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_SONAR_REASONING }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_only_sonar_reasoning_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_ONLY_SONAR_REASONING_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_ONLY_SONAR_REASONING_PRO }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

  bot_deepseek_r1_gpt_4o_search_preview:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_GPT_4O_SEARCH_PREVIEW'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_GPT_4O_SEARCH_PREVIEW }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  bot_deepseek_r1_gemini_2_5_pro_grounding:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_GEMINI_2_5_PRO_GROUNDING'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_GEMINI_2_5_PRO_GROUNDING }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  bot_deepseek_r1_exa_smart_searcher:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_EXA_SMART_SEARCHER'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_EXA_SMART_SEARCHER }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_EXA_API_KEY: ${{ secrets.EXA_API_KEY }}

  bot_deepseek_r1_ask_exa_pro:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_ASK_EXA_PRO'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_ASK_EXA_PRO }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_EXA_API_KEY: ${{ secrets.EXA_API_KEY }}

  bot_deepseek_r1_deepnews:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_DEEPNEWS'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_DEEPNEWS }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o3_high:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_HIGH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_HIGH_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o3:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  bot_o4_mini_high:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O4_MINI_HIGH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O4_MINI_HIGH_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  bot_o4_mini:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O4_MINI_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O4_MINI_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_4_1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_4_1_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_4_1_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_4_1_mini:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_4_1_MINI_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_4_1_MINI_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_4_1_nano:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_4_1_NANO_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_4_1_NANO_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  # bot_gemini_2_5_flash_preview:
  #   uses: ./.github/workflows/run-bot-launcher.yaml
  #   with:
  #     bot_name: 'METAC_GEMINI_2_5_FLASH_PREVIEW_TOKEN'
  #   secrets:
  #     INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_FLASH_PREVIEW_TOKEN }}
  #     INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  #     INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  #     INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
  #     INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1_high:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O1_HIGH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O1_HIGH_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O1_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O1_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o1_mini:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O1_MINI_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O1_MINI_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o3_mini_high:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_MINI_HIGH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_MINI_HIGH_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o3_mini:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_MINI_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_MINI_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gpt4o:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GPT_4O_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_4O_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gpt4o_mini:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GPT_4O_MINI_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_4O_MINI_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gpt3_5_turbo:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GPT_3_5_TURBO_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_3_5_TURBO_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_claude_3_7_sonnet_latest_thinking:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_CLAUDE_3_7_SONNET_LATEST_THINKING_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_CLAUDE_3_7_SONNET_LATEST_THINKING_TOKEN }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_claude_3_7_sonnet_latest:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_CLAUDE_3_7_SONNET_LATEST_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_CLAUDE_3_7_SONNET_LATEST_TOKEN }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_claude_3_5_sonnet_latest:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_CLAUDE_3_5_SONNET_LATEST_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_CLAUDE_3_5_SONNET_LATEST_TOKEN }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_claude_3_5_sonnet_20240620:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_CLAUDE_3_5_SONNET_20240620_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_CLAUDE_3_5_SONNET_20240620_TOKEN }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_gemini_2_5_pro_preview:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_5_PRO_PREVIEW_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_PRO_PREVIEW_TOKEN }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_gemini_2_0_flash:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_0_FLASH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_0_FLASH_TOKEN }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_llama_4_maverick_17b:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_LLAMA_4_MAVERICK_17B_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_LLAMA_4_MAVERICK_17B_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_qwen_2_5_max:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_QWEN_2_5_MAX_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_QWEN_2_5_MAX_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek_r1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek_v3:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_V3_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_V3_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_grok_3_latest:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GROK_3_LATEST_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GROK_3_LATEST_TOKEN }}
      INPUT_XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_grok_3_mini_latest_high:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GROK_3_MINI_LATEST_HIGH_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GROK_3_MINI_LATEST_HIGH_TOKEN }}
      INPUT_XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_uniform_probability:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_UNIFORM_PROBABILITY_BOT_TOKEN'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_UNIFORM_PROBABILITY_BOT_TOKEN }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
