name: Run Bot for the Metaculus Cup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *" # runs at midnight every 3 days

# Add concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

# Daily job to run the forecast bot
jobs:
  bot_gpt4o:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GPT_4O_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_4O_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O1_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O1_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_gemini_2_5_pro_preview:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_GEMINI_2_5_PRO_PREVIEW_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_2_5_PRO_PREVIEW_TOKEN }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

  bot_o3_high_token:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_O3_HIGH_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_O3_HIGH_TOKEN }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek_r1:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_DEEPSEEK_R1_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_llama_4_maverick_17b:
    uses: ./.github/workflows/run-bot-launcher.yaml
    with:
      bot_name: 'METAC_LLAMA_4_MAVERICK_17B_TOKEN+metaculus-cup'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_LLAMA_4_MAVERICK_17B_TOKEN }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
